### ISSUE TITLE
Student work using ViveTrack

### ISSUE THREAD

**Issue by garciadelcastillo** [ccc159/ViveTrack#1]
Hi @ccc159!

This is not really an issue, but just wanted to share some work that students in my class did using the ViveTrack plug-in for GH: https://www.youtube.com/watch?v=HEYYl0M3ynk

Super helpful as usual, thank you so much for having shared this with the world! <3

JL

**Comment by jingcheng-chen** [comment]
@garciadelcastillo Very glad to see such talent students to work with it! These are amazing works!

Thanks for sharing :)
Chen
