### ISSUE TITLE
你好 想请教一个简单的问题，

### ISSUE THREAD

**Issue by archuleo** [ccc159/ViveTrack#4]
![image](https://user-images.githubusercontent.com/68276105/87411506-65e19580-c5fa-11ea-902f-20cf0b58a2b4.png)

你好，我是建筑学的学生，目前在研究AR FABRICATION.
我想请问一下为什么我这里似乎少了几个功能键，尤其是确定平面的那个。
另外我的GHA文件没有unlock的选项。

谢谢

**Comment by archuleo** [comment]
hello?
////

**Comment by jingcheng-chen** [comment]
closing this as it is not a bug but more personal inquiry
